#When it happens
on:
  push: #push {}
    branches:
      - main #When someone pushes the main
  workflow_dispatch: #When we click

#What is does
jobs: # What to do
  quality_checker:
    name: "Quality Check"
    runs-on: "ubuntu-latest"
    steps:
      #Get access to repo code
      - name: "Get repo"
        uses: actions/checkout@v6 #Use a built-in, exisiting action
        
      - name: "Install Python"
        uses: actions/setup-python@v6
        
      - name: "Install libraries"
        run: pip install -r requirements.txt

      - name: "Run pytest"
        run: pytest
      
      
    
