#When it happens
on:
  push: #push {}
    branches:
      - main #When someone pushes the main
  workflow_dispatch: #When we click

#What is does
jobs: # What to do
  example:
    name: "Example job"
    runs-on: "ubuntu-latest"
    steps: #What specifically to do (Just shell commands lol)
      - name: "Step 1"
        run: echo "hi" #Run a basic shell command
      - name: "Step 2"
        run: echo "hi again" #Run a basic shell command
      
    
